name: stream_bronze_to_silver_events
domain: clickstream
job_type: spark_streaming
entrypoint: spark_apps/streaming/bronze_to_silver_events.py
spark_master: spark://spark-master:7077
packages:
  - io.delta:delta-spark_2.12:3.2.0
spark_conf:
  spark.jars.ivy: /tmp/.ivy2
  spark.executor.cores: "1"
  spark.executor.memory: "1G"
  spark.cores.max: "1"
args: {}
dependencies: []
schedule: always_on