name: stream_kafka_to_bronze
domain: clickstream
job_type: spark_streaming
entrypoint: spark_apps/streaming/kafka_to_bronze.py
spark_master: spark://spark-master:7077
packages:
  - io.delta:delta-spark_2.12:3.2.0
  - org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.1
  - org.apache.hadoop:hadoop-aws:3.3.4
spark_conf:
  spark.jars.ivy: /tmp/.ivy2
  spark.executor.cores: "1"
  spark.executor.memory: "1G"
  spark.cores.max: "1"
args: {}
dependencies: []
schedule: always_on