services:
  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "8091:8080"
    environment:
      COLLECTOR_URL: http://collector:8000/collect
      PUBLIC_COLLECTOR_URL: http://localhost:8000/collect
    networks:
      - rltm_shared_net

networks:
  rltm_shared_net:
    external: true